jenkins:
  image: "jenkins:2.3"
  ports:
    - "8080:8080"
  labels:
    io.rancher.sidekicks: jenkins-datavolume
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - jenkins-datavolume
jenkins-datavolume:
  image: "busybox"
  volumes:
    - /var/jenkins_home
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
