nexus-server:
  ports:
  - 8081:8081/tcp
  labels:
    io.rancher.sidekicks: nexus-data
  hostname: ${nexus_hostname}
  image: sonatype/nexus:2.13.0-01
  entrypoint:
  - mkdir /etc/nexus && chown -R 200 /etc/nexus
  volumes_from:
  - nexus-data

nexus-data:
  labels:
    io.rancher.container.start_once: 'true'
  hostname: nexusdata
  image: busybox
  volumes:
  - /etc/nexus:/sonatype-work

