nexus-server:
  ports:
  - 8081:8081/tcp
  labels:
    io.rancher.sidekicks: nexus-data
  hostname: ${nexus_hostname}
  image: sonatype/nexus3:3.0.0
  volumes_from:
  - nexus-data

nexus-data:
  labels:
    io.rancher.container.start_once: 'true'
  hostname: nexusdata
  image: busybox
  entrypoint:
  - /bin/true
  volumes:
  - /etc/nexus:/nexus-data

