gitlab-runner:
  image: gitlab/gitlab-runner:v1.3.0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - gitlab-runner-data

gitlab-runner-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitlab-runner-data
  image: busybox
  - /srv/gitlab-runner/config:/etc/gitlab-runner
